### ISSUE TITLE
setup project environment

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/demo-etl-airflow#1]
Task: https://n-abledev.atlassian.net/browse/DA-2900?atlOrigin=eyJpIjoiNzkzOWNhNWUyYThlNGQ4Nzk4MjYyNjU0NmFlNjU0OGYiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #2 from koshitha-nable/ka/feature/001/setup_project_env
