### ISSUE TITLE
Source data extraction from multiple datasources

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/demo-etl-airflow#3]
Task:https://n-abledev.atlassian.net/browse/DA-2900?atlOrigin=eyJpIjoiNDQ4M2YwYWQ5MTMwNDAxODg3ZDkyODRhNDIxMTIyMDQiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #4 from koshitha-nable/ka/feature/003/extract_data_src
