### ISSUE TITLE
create transformations and load data to fact and dimensions

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/demo-etl-airflow#5]
- https://n-abledev.atlassian.net/browse/DA-2930?atlOrigin=eyJpIjoiNjYxMjA1NDc3NDkxNDc0YjlmNWM1MWFjMTU3MmYwMzkiLCJwIjoiaiJ9
- https://n-abledev.atlassian.net/browse/DA-2933?atlOrigin=eyJpIjoiZjZmYWEwYWY2OTQ1NGYwY2JjNWQ5ZGYxYTNmNDQ0MGIiLCJwIjoiaiJ9
- https://n-abledev.atlassian.net/browse/DA-2931?atlOrigin=eyJpIjoiMDAzYzM4ZmM2ZDczNGM1NGFkNzhlZjYzM2ZiOTM0NTQiLCJwIjoiaiJ9
- https://n-abledev.atlassian.net/browse/DA-2935?atlOrigin=eyJpIjoiNTlmYTQ5YWRiN2MyNDBmMGIwYzBmNGQ5NTdkNmU0YzkiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #6 from koshitha-nable/ka/feature/005/transform_data_load_fact_dim
