### ISSUE TITLE
Intermediate data cleaning and dimension table validation and monitoring

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/demo-etl-airflow#7]
https://n-abledev.atlassian.net/browse/DA-3009?atlOrigin=eyJpIjoiZTcyNGJlNGRiM2UzNDdkZjhjZDJkYjMwYTVkNDZkNDkiLCJwIjoiaiJ9

https://n-abledev.atlassian.net/browse/DA-3007?atlOrigin=eyJpIjoiYTAwYWYyYWZjNmZlNGM4MThkNDgyNGI3NDIwMTczOGYiLCJwIjoiaiJ9

https://n-abledev.atlassian.net/browse/DA-3010?atlOrigin=eyJpIjoiMzUwZTNhZmQ4ZDhlNGM1MGE1MjhhNjdjODRjOWMyZWYiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #8 from koshitha-nable/ka/feature/007/validate_data_and_monitoring

**Comment by piranavan-nable** [comment]
@koshitha-nable  delete the junk branch and close this issue
